### PR TITLE
Completed prep-html-syntax

### PR DESCRIPTION
**Pull request by Han-Zhang-Code**
Screenshot 2022-04-16 142706

### CODE REVIEW

**Review by thebearingedge — CHANGES_REQUESTED** [review]
Please structure this in a proper HTML document structure with doctype, html, body, etc

**Comment by Han-Zhang-Code** [comment]
Screenshot 2022-04-16 150520
skeleton added, but not sure why there is a red line under "<html>"

**Review by thebearingedge — CHANGES_REQUESTED** [review]
Hi Yuhan, the red error is there because your document is missing a head and title.

**Comment by Han-Zhang-Code** [comment]
Screenshot 2022-04-18 110930
Thank you for pointing out, I have fixed the issue

**Review by thebearingedge — APPROVED** [review]

**Pull request merged**
